version: "3.1"
services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./frontend/dist:/srv/www/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - nodejs
      - python
  nodejs:
    image: node:alpine
    environment:
      NODE_ENV: production
    working_dir: /home/app
    restart: always
    ports:
      - "8001:3000"
    volumes:
      - ./node-app:/home/app
    depends_on:
      - php
    command: ["npm", "run", "start:dev"]
  php:
    image: webdevops/php-apache-dev:8.2
    volumes:
      - ./php-app:/app  # Mount the PHP app to /app directory in the container
    ports:
      - "8002:80"
    environment:
      - WEB_DOCUMENT_ROOT=/app/web  # Point to the Yii web folder

  python:
    image: python:3.10-alpine
    restart: always
    volumes:
      - ./python-app:/app
    working_dir: /app
    ports:
      - "8003:5000"
    environment:
      - FLASK_APP=main.py
    command: >
      sh -c "
      pip install flask 
      && flask run --host=0.0.0.0
      "

