services:
  nginx:
    image: nginx:alpine
    container_name: nginx-conf
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - webnet

  api:
    image: node:alpine
    container_name: demo-alpine
    working_dir: /usr/src/app
    volumes:
      - ./demo-app:/usr/src/app
    command: sh -c "npm install && npm install class-validator && npm install class-transformer && npm start dev"
    depends_on:
      - pg
    ports:
      - "8082:80"
    networks:
      - webnet

    # command: sh -c "npm install && npm install class-validator && npm install class-transformer && npm run seed && npm start dev"

  pg:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: demo-app
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - webnet
      
volumes:
  pg-data:

networks:
  webnet:
    driver: bridge
